# Generated by Django 3.0.7 on 2020-08-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoVCImanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvci',
            old_name='lended',
            new_name='lent',
        ),
        migrations.RenameField(
            model_name='vci',
            old_name='lended',
            new_name='lent',
        ),
    ]
