# Generated by Django 3.0.7 on 2020-09-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoVCImanage', '0003_auto_20200907_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubsidiary',
            name='idSubsidiary',
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='idSubsidiary',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
