# Generated by Django 3.0.7 on 2020-09-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoVCImanage', '0005_auto_20200922_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('idWorkshop', models.AutoField(primary_key=True, serialize=False)),
                ('workshopName', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('postal', models.CharField(max_length=200)),
                ('contacName', models.CharField(max_length=200)),
                ('contactSurname', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
