# Generated by Django 3.0.7 on 2020-09-24 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoVCImanage', '0007_historicalworkshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvci',
            name='workshop',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='demoVCImanage.Workshop'),
        ),
        migrations.AddField(
            model_name='vci',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demoVCImanage.Workshop'),
        ),
    ]
