# Generated by Django 3.0.7 on 2020-09-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoVCImanage', '0008_auto_20200924_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalespersondelphi',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalsalespersondelphi',
            name='postal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalsalespersondelphi',
            name='street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salespersondelphi',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salespersondelphi',
            name='postal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salespersondelphi',
            name='street',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
